CREATE TABLE IF NOT EXISTS boats (
    id SERIAL PRIMARY KEY,
    name TEXT NOT NULL,
    mmsi TEXT NOT NULL UNIQUE,
    color TEXT NOT NULL DEFAULT '#3388ff',
    track_style TEXT NOT NULL DEFAULT 'solid',
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

ALTER TABLE boats ADD COLUMN IF NOT EXISTS track_style TEXT NOT NULL DEFAULT 'solid';

CREATE TABLE IF NOT EXISTS positions (
    id SERIAL PRIMARY KEY,
    mmsi TEXT NOT NULL,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    speed DOUBLE PRECISION,
    heading DOUBLE PRECISION,
    timestamp TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS positions_mmsi_timestamp_idx ON positions (mmsi, timestamp DESC);

CREATE TABLE IF NOT EXISTS saved_points (
    id SERIAL PRIMARY KEY,
    lat DOUBLE PRECISION NOT NULL,
    lon DOUBLE PRECISION NOT NULL,
    name TEXT NOT NULL DEFAULT '',
    notes TEXT NOT NULL DEFAULT '',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);
